kind: Template
apiVersion: v1
metadata:
  name: workload-web-app
objects:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: workload-web-app
    spec:
      replicas: 1
      selector:
        app: workload-web-app
        deploymentconfig: workload-web-app
      template:
        metadata:
          labels:
            app: workload-web-app
            deploymentconfig: workload-web-app
          annotations:
        spec:
          containers:
            - name: workload-web-app
              image: ${WORKLOAD_WEB_APP_IMAGE}
              ports:
                - containerPort: ${{PORT}}
                  protocol: TCP
              imagePullPolicy: Always
              env:
                - name: PORT
                  value: ${PORT}
                - name: AMQ_ADDRESS
                  value: ${AMQ_ADDRESS}
                - name: AMQ_QUEUE
                  value: ${AMQ_QUEUE_NAME}
                - name: AMQ_CONSOLE_URL
                  value: ${AMQ_CONSOLE_URL}
                - name: AMQ_CONSOLE_USER
                  value: asdf
                - name: AMQ_CONSOLE_PWD
                  value: asdf
                - name: THREE_SCALE_URL
                  value: ${THREE_SCALE_URL}
                - name: ENVIRONMENT
                  value: production
                - name: AMQ_CRUD_NAMESPACE
                  value: ${AMQ_CRUD_NAMESPACE}
                - name: RHSSO_SERVER_URL
                  value: ${RHSSO_SERVER_URL}
                - name: RHSSO_USER
                  valueFrom:
                    secretKeyRef:
                      name: rhsso-secret
                      key: RHSSO_USER
                - name: RHSSO_PWD
                  valueFrom:
                    secretKeyRef:
                      name: rhsso-secret
                      key: RHSSO_PWD
          serviceAccountName: workload-web-app
          restartPolicy: Always
  - kind: Service
    apiVersion: v1
    metadata:
      name: workload-web-app
      labels:
        app: workload-web-app
        deploymentconfig: workload-web-app
    spec:
      ports:
        - name: http
          protocol: TCP
          port: ${{PORT}}
          targetPort: ${{PORT}}
      selector:
        deploymentconfig: workload-web-app
      sessionAffinity: None
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      name: workload-web-app
  - kind: Role
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: workload-web-app
    rules:
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - "*"
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: workload-web-app
    subjects:
      - kind: ServiceAccount
        name: workload-web-app
    roleRef:
      kind: Role
      apiGroup: rbac.authorization.k8s.io
      name: workload-web-app
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: workload-web-app
      labels:
        monitoring-key: middleware
    spec:
      endpoints:
        - port: http
      selector:
        matchLabels:
          app: workload-web-app
  - kind: Role
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: rhmi-prometheus-k8s
    rules:
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - ""
        resources:
          - services
          - endpoints
          - pods
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: rhmi-prometheus-k8s
    subjects:
      - kind: ServiceAccount
        name: prometheus-k8s
        namespace: openshift-monitoring
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: rhmi-prometheus-k8s
  - kind: Role
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: rhmi-operator
    rules:
      - apiGroups:
          - rbac.authorization.k8s.io
        resources:
          - roles
          - rolebindings
        verbs:
          - get
          - list
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: rhmi-operator
    subjects:
      - kind: ServiceAccount
        name: rhmi-operator
        namespace: redhat-rhmi-operator
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: rhmi-operator
parameters:
  - name: WORKLOAD_WEB_APP_IMAGE
    description: "Alternative image for local development"
    value: "quay.io/integreatly/workload-web-app:master"
  - name: PORT
    description: Port number
    value: "8080"
  - name: AMQ_ADDRESS
    description: The URL to connect to an AMQ address
  - name: AMQ_QUEUE_NAME
    description: The queue name to use for the AMQ address
  - name: AMQ_CONSOLE_URL
    description: The AMQ console URL for testing the console
  - name: AMQ_CONSOLE_USER
    description: The RHMI user to login to AMQ console
  - name: AMQ_CONSOLE_PWD
    description: The password for the RHMI user to login to AMQ console
  - name: RHSSO_SERVER_URL
    description: The RHSSO Server URL
  - name: RHSSO_USER
    description: The username for RHSSO login
  - name: RHSSO_PWD
    description: The Password for RHSSO login
  - name: THREE_SCALE_URL
    description: The API URL protected by 3scale
  - name: AMQ_CRUD_NAMESPACE
    description: The namespace were to create AMQ AddressSpaces and Addresses
